### ISSUE TITLE
有关部署的相关问题

### ISSUE THREAD

**Issue by ucmer2018** [FreudFan/online-exam-backend#3]
请问作者，有关项目的jdk、tomcat版本等有详细介绍吗？

**Comment by FreudFan** [comment]
jdk版本为1.8，tomcat版本为tomcat9，tomcat使用的是内嵌式tomcat，不需要额外部署。导入项目时使用maven导入即可。

**Comment by ucmer2018** [comment]
我用的宝塔来部署项目，因为是第一次部署jsp项目，不太会操作。有空的话希望作者可以指教一下，谢谢😁

**Comment by FreudFan** [comment]
- 您好，这个是一个app应用的后端项目，只提供restful接口，只有接口文档页面，没有应用前端页面。项目里的jsp页面是为了定向到接口文档查询路径。

- 这个项目目前还在开发中，代码更新频率较大，预计3月份才能开发完所有功能，目前还没有被部署过，只能在开发环境idea中本地运行。

- 关于部署：方法是把项目打包成可执行的jar包，然后执行这个jar包运行了。main类是OnlineExamApplication.java类。可能会报出文件找不到异常，需修改"application.properties"配置的文件路径，和项目里其他若干配置文件配置路径。

- 关于宝塔：不好意思宝塔我没用过，不知道怎么部署jar包，你可以先尝试在本地跑起来，然后直接部署到服务器上。使用 java -jar 包名.jar 执行。

- 不好意思此回答可能无法帮到您。您如果想学习部署项目的话，本项目不太适合学习部署，可以移步到其他spring mvc项目看看。抱歉本项目由于不易部署浪费了您宝贵的时间，我深感歉意。
